project_name: quiz
release:
  github:
    owner: babkamen
    name: quiz
  name_template: '{{.Tag}}'
milestones:
- repo:
    owner: babkamen
    name: quiz
  name_template: '{{ .Tag }}'
scoop:
  name: quiz
  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com
  commit_msg_template: Scoop update for {{ .ProjectName }} version {{ .Tag }}
builds:
  -
    env:
      - CGO_ENABLED=0
      - GO386=softfloat
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
archives:
  -
    replacements:
      darwin: MacOS
      linux: Linux
      windows: Windows
      386: 32-bit
      amd64: 64-bit
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT-{{ .ShortCommit }}'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
  algorithm: sha256
dist: dist
source:
  name_template: '{{ .ProjectName }}-{{ .Version }}'
  format: tar.gz
gomod:
  gobinary: go
announce:
  twitter:
    message_template: '{{ .ProjectName }} {{ .Tag }} is out! Check it out at {{ .GitURL
      }}/releases/tag/{{ .Tag }}'
github_urls:
  download: https://github.com
gitlab_urls:
  download: https://gitlab.com
